### ISSUE TITLE
Default input parameter says "CommunityParcels"

### ISSUE THREAD

**Issue by lindsayking** [Esri/community-addresses-python#1]
@busbus  The default input for the Feature Service Name parameter says "CommunityParcels".  

![image](https://cloud.githubusercontent.com/assets/4316336/7465044/8d90be62-f27e-11e4-8d79-93e926d393ed.png)

**Comment by busbus** [comment]
Fixed with commit 

https://github.com/Esri/community-addresses-python/commit/3b87623a7597965fcd552c4a6ec1029b2908ca5a
