### ISSUE TITLE
problem with service on sampleserver6

### ISSUE THREAD

**Issue by jgravois** [Esri/community-addresses-python#3]
this is most definitely probably _not_ the best place to report, but a shot in the dark is better than nothing. 

an esteemed former colleague noticed that the feature layer on the sample server below has a unique value renderer defined using a field that is **not** visible in the service itself.

http://sampleserver6.arcgisonline.com/arcgis/rest/services/CommunityAddressing/MapServer/0

``` js
drawingInfo: {
  renderer: {
    type: "uniqueValue",
      field1: "status",
      ...
```

anyone know who maintains the service?

see Esri/esri-leaflet-renderers#115 for more info.

**Comment by LindsayThomas** [comment]
@jgravois SampleServer6 ... is the server team. I think...
